# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Reality Update
email: ru.informatics@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Reality Update strive to bring legitimate information to the people
  who are looking for ways to be a better version of themselves. We hope
  to give as much as we can, so anyway reader's can give back to promote 
  this blog means everything.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: N/A
github_username:  matt1moore

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman